name: "trufflehog"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  scan:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"  # v6.0.2
        with:
          fetch-depth: 0
      - uses: "trufflesecurity/trufflehog@7f4e37db2d928c18ddd7ddf0604f8f7d1f5793ec"  # v3.93.0
        with:
          extra_args: "--results=verified,unknown"
